import { Industry } from '../enums';

export function asIndustry(industry: string) {
  const industries: Record<string, Industry> = {
    '水泥工業': Industry.Cement,
    '食品工業': Industry.Food,
    '塑膠工業': Industry.Plastic,
    '紡織纖維': Industry.Textiles,
    '電機機械': Industry.ElectricMachinery,
    '電器電纜': Industry.ElectricalAndCable,
    '玻璃陶瓷': Industry.GlassAndCeramic,
    '造紙工業': Industry.PaperAndPulp,
    '鋼鐵工業': Industry.IronAndSteel,
    '橡膠工業': Industry.Rubber,
    '汽車工業': Industry.Automobile,
    '建材營造業': Industry.BuildingMaterialsAndConstruction,
    '航運業': Industry.ShippingAndTransportation,
    '觀光餐旅': Industry.TourismAndHospitality,
    '金融保險業': Industry.FinancialAndInsurance,
    '貿易百貨業': Industry.TradingAndConsumerGoods,
    '綜合': Industry.Miscellaneous,
    '其他業': Industry.Other,
    '化學工業': Industry.Chemical,
    '生技醫療業': Industry.BiotechnologyAndMedicalCare,
    '油電燃氣業': Industry.OilGasAndElectricity,
    '半導體業': Industry.Semiconductors,
    '電腦及週邊設備業': Industry.ComputerAndPeripheralEquipment,
    '光電業': Industry.Optoelectronics,
    '通信網路業': Industry.CommunicationsTechnologyAndInternet,
    '電子零組件業': Industry.ElectronicPartsComponents,
    '電子通路業': Industry.ElectronicProductsDistirbution,
    '資訊服務業': Industry.InformationService,
    '其他電子業': Industry.OtherElectronics,
    '文化創意業': Industry.CulturalAndCreative,
    '農業科技業': Industry.AgriculturalTechnology,
    '電子商務': Industry.Ecommerce,
    '綠能環保': Industry.GreenEnergyAndEnvironmentalServices,
    '數位雲端': Industry.DigitalAndCloudServices,
    '運動休閒': Industry.SportsAndLeisure,
    '居家生活': Industry.Household,
    '管理股票': Industry.ManagedStock,
    '無所屬產業': Industry.None,
  };
  return industries[industry] ?? Industry.None;
}
