import { Exchange, Market, Index } from '../enums';

export function getMarketIndices(options?: { market: Market }) {
  const indices = [
    { symbol: Index.TAIEX, name: '發行量加權股價指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't00' },
    { symbol: Index.NonFinance, name: '未含金融指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't001' },
    { symbol: Index.NonElectronics, name: '未含電子指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't002' },
    { symbol: Index.NonFinanceNonElectronics, name: '未含金融電子指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't003' },
    { symbol: Index.Cement, name: '水泥類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't01' },
    { symbol: Index.Food, name: '食品類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't02' },
    { symbol: Index.Plastic, name: '塑膠類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't03' },
    { symbol: Index.CementAndCeramic, name: '水泥窯製類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't011' },
    { symbol: Index.PlasticAndChemical, name: '塑膠化工類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't031' },
    { symbol: Index.Electrical, name: '機電類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't051' },
    { symbol: Index.Textiles, name: '紡織纖維類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't04' },
    { symbol: Index.ElectricMachinery, name: '電機機械類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't05' },
    { symbol: Index.ElectricalAndCable, name: '電器電纜類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't06' },
    { symbol: Index.ChemicalBiotechnologyAndMedicalCare, name: '化學生技醫療類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't07' },
    { symbol: Index.Chemical, name: '化學類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't21' },
    { symbol: Index.BiotechnologyAndMedicalCare, name: '生技醫療類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't22' },
    { symbol: Index.GlassAndCeramic, name: '玻璃陶瓷類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't08' },
    { symbol: Index.PaperAndPulp, name: '造紙類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't09' },
    { symbol: Index.IronAndSteel, name: '鋼鐵類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't10' },
    { symbol: Index.Rubber, name: '橡膠類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't11' },
    { symbol: Index.Automobile, name: '汽車類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't12' },
    { symbol: Index.Electronics, name: '電子工業類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't13' },
    { symbol: Index.Semiconductors, name: '半導體類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't24' },
    { symbol: Index.ComputerAndPeripheralEquipment, name: '電腦及週邊設備類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't25' },
    { symbol: Index.Optoelectronics, name: '光電類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't26' },
    { symbol: Index.CommunicationsTechnologyAndInternet, name: '通信網路類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't027' },
    { symbol: Index.ElectronicPartsComponents, name: '電子零組件類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't28' },
    { symbol: Index.ElectronicProductsDistirbution, name: '電子通路類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't29' },
    { symbol: Index.InformationService, name: '資訊服務類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't30' },
    { symbol: Index.OtherElectronics, name: '其他電子類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't31' },
    { symbol: Index.BuildingMaterialsAndConstruction, name: '建材營造類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't14' },
    { symbol: Index.ShippingAndTransportation, name: '航運類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't15' },
    { symbol: Index.TourismAndHospitality, name: '觀光餐旅類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't16' },
    { symbol: Index.FinancialAndInsurance, name: '金融保險類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't17' },
    { symbol: Index.TradingAndConsumerGoods, name: '貿易百貨類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't18' },
    { symbol: Index.OilGasAndElectricity, name: '油電燃氣類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't23' },
    { symbol: Index.Other, name: '其他類指數', exchange: Exchange.TWSE, market: Market.TSE, alias: 't20' },
    { symbol: Index.GreenEnergyAndEnvironmentalServices, name: '綠能環保類指數', exchange: Exchange.TWSE, market: Market.TSE },
    { symbol: Index.DigitalAndCloudServices, name: '數位雲端類指數', exchange: Exchange.TWSE, market: Market.TSE },
    { symbol: Index.SportsAndLeisure, name: '運動休閒類指數', exchange: Exchange.TWSE, market: Market.TSE },
    { symbol: Index.Household, name: '居家生活類指數', exchange: Exchange.TWSE, market: Market.TSE },
    { symbol: Index.TPEX, name: '櫃買指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o00' },
    { symbol: Index.TPExTextiles, name: '櫃買紡纖類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o04' },
    { symbol: Index.TPExElectricMachinery, name: '櫃買機械類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o05' },
    { symbol: Index.TPExIronAndSteel, name: '櫃買鋼鐵類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o10' },
    { symbol: Index.TPExElectronic, name: '櫃買電子類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o13' },
    { symbol: Index.TPExBuildingMaterialsAndConstruction, name: '櫃買營建類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o14' },
    { symbol: Index.TPExShippingAndTransportation, name: '櫃買航運類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o15' },
    { symbol: Index.TPExTourismAndHospitality, name: '櫃買觀光餐旅類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o16' },
    { symbol: Index.TPExChemical, name: '櫃買化工類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o21' },
    { symbol: Index.TPExBiotechnologyAndMedicalCare, name: '櫃買生技醫療類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o22' },
    { symbol: Index.TPExSemiconductors, name: '櫃買半導體類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o24' },
    { symbol: Index.TPExComputerAndPeripheralEquipment, name: '櫃買電腦及週邊類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o25' },
    { symbol: Index.TPExOptoelectronic, name: '櫃買光電業類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o26' },
    { symbol: Index.TPExCommunicationsAndInternet, name: '櫃買通信網路類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o27' },
    { symbol: Index.TPExElectronicPartsComponents, name: '櫃買電子零組件類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o28' },
    { symbol: Index.TPExElectronicProductsDistribution, name: '櫃買電子通路類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o29' },
    { symbol: Index.TPExInformationService, name: '櫃買資訊服務類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o30' },
    { symbol: Index.TPExCulturalAndCreative, name: '櫃買文化創意業類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o32' },
    { symbol: Index.TPExOtherElectronic, name: '櫃買其他電子類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o31' },
    { symbol: Index.TPExOther, name: '櫃買其他類指數', exchange: Exchange.TPEx, market: Market.OTC, alias: 'o20' },
    { symbol: Index.TPExGreenEnergyAndEnvironmentalServices, name: '櫃買綠能環保類指數', exchange: Exchange.TPEx, market: Market.OTC },
    { symbol: Index.TPExDigitalAndCloudServices, name: '櫃買數位雲端類指數', exchange: Exchange.TPEx, market: Market.OTC },
    { symbol: Index.TPExHousehold, name: '櫃買居家生活類指數', exchange: Exchange.TPEx, market: Market.OTC },
  ];
  /* istanbul ignore next */
  return options?.market ? indices.filter(index => index.market === options.market) : indices;
}
